// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Parameterized INSERT using positional arguments ($1, $2, $3) for SQL injection protection
	// RETURNING clause fetches newly created row in a single roundtrip, saving a subsequent SELECT
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Simple primary-key targeted DELETE operation
	// CASCADE behavior depends on foreign key constraints defined in schema
	// Returns no rows (exec) since we don't need the deleted data
	DeleteAccount(ctx context.Context, id int64) error
	// Direct primary key lookup ensures O(1) performance via B-tree index
	// LIMIT 1 optimizes query planning - tells PostgreSQL to stop after first match
	GetAccount(ctx context.Context, id int64) (Account, error)
	// Direct primary key lookup ensures O(1) performance via B-tree index
	// LIMIT 1 optimizes query planning - tells PostgreSQL to stop after first match
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	// Direct primary key lookup ensures O(1) performance via B-tree index
	// LIMIT 1 optimizes query planning - tells PostgreSQL to stop after first match
	GetUser(ctx context.Context, username string) (User, error)
	// Paginated query pattern with LIMIT/OFFSET for incremental data retrieval
	// ORDER BY ensures stable pagination even with concurrent modifications
	// Ordering by primary key is efficient due to clustered index usage
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Single-row UPDATE targeting primary key for efficient index scan
	// RETURNING clause eliminates need for separate SELECT after UPDATE
	// This is an absolute-value update (overwrites existing balance)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	// Atomic increment/decrement pattern for concurrent safety
	// Uses SET balance = balance + $2 for race-condition-free operation
	// Critical for maintaining consistency under concurrent modifications
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
